names:
- doll
- key ring
- keyboard
- memo
- monitor
- monitor light
- mouse
- paper money
- pen
- phone
- speaker
- tablet
- wallet
nc: 13
path: D:/vision/yolo_dataset
test: test/images
train: train/images
val: valid/images
